export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_ITEMS = 'ADD_ITEMS';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
